### ISSUE TITLE
Lightning Specification Meeting 2024/05/20

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#1164]
The meeting will take place on Monday 2024/05/20 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Spec clean-up #1092
- [x] Optional `channel_update` in error onions #1163
- [x] Offers #798
- [x] Quiescence #869
  - @rustyrussell can you (or someone else with access to the branch) rebase the PR? We've started cross-compat tests between eclair and lnd, it's looking good, so we should be able to merge it soon
  - there are also a couple of comments asking for some small additions to clarify a few subtleties, but nothing major
- [x] Splicing #863 #1160
- [x] Liquidity ads #878 #1145 #1153
- [x] Dynamic Commitments #1117 vs Upgrade on Reestablish #868
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Async payments #1149
- [x] Peer storage backup #881 or #1110
- [x] Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27
- [x] DNS-based offers #1136
- [x] Attributable errors #1044
- [x] Clarify `channel_reestablish` requirements #1049 or #1051

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [x] Constant size failure onion decryption #1154 
- [x] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Simplified mutual close #1096~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
I won't be able to attend this meeting (I'll be on vacation during the beginning of next week), I've reviewed pending PRs and updated mine, looking forward to your comments!

**Comment by Roasbeef** [comment]
offers:
  * change to have a blinded path or a node ID
  * wanting node ID to be optional if a node ID exists

set reconciliation:
  * something to be picked up again once taproot gossip is a thing 
  * everything will be block height based, timestamps not compatible with approaches

gossip 1.5:
  * CLN working on a version
     * also looking forward to block height based rate limiting as well
  * legacy channel broadcast
     * how long do we broadcast both of them?
     * also question of the block height buffer as well
        * does this add additional state?

stfu:
  * have done prelim introp testing w/ lnd and eclair
    * not fully tested in context yet, but able to verify traffic stops and deferred stuff is reconciled on reconnect
  * PR to rusty's branch to clarify some additional requirements: https://github.com/rustyrussell/lightning-rfc/pull/15
     * clarifies how down stream protocols should interpret cool 

splicing:
   * new splicing PR: https://github.com/lightning/bolts/pull/1160

liquidity ads:
   * main PR: https://github.com/lightning/bolts/pull/1153 

dyn commitment:
    * discussion re diff upgrade paths: https://delvingbitcoin.org/t/upgrading-existing-lightning-channels/881/1
    * proposal to split off the kick off stuff, depends on appetite
       * also the vector to update just normal channels to anchor zero fee

taproot:
   * in interop mode

peer storage backup:
    * lnd implementation on going 
    * LDK implementation WIP now as well, CLN implementation going thru iterations
    * ready for fresh review 

channel jamming:
  * updated the bLIP, call for another round of review
    * close to merging it 

rbf coop close:
   * waiting for interop re lock time change
