### ISSUE TITLE
Lightning Specification Meeting 2024/08/26

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#1191]
The meeting will take place on Monday 2024/08/26 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Offers #798
- [x] Channel jamming #1071
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Liquidity ads #878 #1153
- [x] Splicing #863 #1160
- [x] Async payments #1149
- [x] Dynamic Commitments #1117 vs Upgrade on Reestablish #868
- [x] gossip_status #1186 
- [x] Peer storage backup #881 or #1110
- [x] Bolt 12 contacts / mutual message auth: https://delvingbitcoin.org/t/bolt-12-trusted-contacts/1046
- [ ] ~Attributable errors #1044~
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [x] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [x] Simplified mutual close #1096
- [x] Trampoline routing #829 and #836
- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Roasbeef** [comment]
channel jamming:
  * new attack variant discovered by morehouse 
  * working on updating to account for it

taproot chans:
  * got some review from fabrice, roasbeef working on the changes
  * still not updated to use the mini script compatible scripts, will do that in the non-staging bit 
  * rbf co-op:
     * lnd still needing to make change for locktime instead of sequence

taproot gossip:
   * close to revival...
      * near term goal to remove from draft state
      * lnd continuing to work on the new code path


bolt12 contacts:
  * delving post up, not much progress after the initial discussion 
  * 

splicing:
  * CLN working thru set of changes to 

async payments + trampoline:
  * rn trampoline node gets a blinded paths, and relays to blinded paths
     * the issue is that you aren't forced to use it in a privacy safe way
     * so then can use zero hop blinded paths w/ the node themselves 
     * so receivers can make bad blinded paths, revealing more information to the sender's first hop
  * potential work around:
      * add another trampoline hop
      * essentially requires including the blinded path twice
         * may only be an issue if you do trampoline "all the way"
         * so instead can do trampoline blinded hops?

dyn commits:
   * pushed to slim down version, removing some of the funding output conversion
      * few segments that say note for reviewers, guide for reviewers, marking unstable parts
   * **while we're here....default anchors?**
      * eclair stopped accepting non static key anchors
      * two changes:
          1. channel type negotiation by default 
          2. reject all non-anchor channels
      * **most nodes _do_ support anchors these days**

TRUC + v3 + 1p1c:
  * what can we do w/ bitcoind 28 released? 
  * how does it affect the commitment format, etc?
  * good topic for summit


peer storage back up:
   * target for lnd 0.19 
   * interop:
     * does CLN have a full up to date impl?

inbound fees:
  * lnd deployed bLIP that was proposed 
    * discount only for now, RPC will reject anything that's positive
