### ISSUE TITLE
Lightning Specification Meeting 2024/09/09

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#1195]
The meeting will take place on Monday 2024/09/09 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Liquidity ads #878 #1153
- [x] Splicing #863 #1160
- [x] Offers #798
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Dynamic Commitments #1117 vs Upgrade on Reestablish #868
- [ ] ~Channel jamming #1071~
- [ ] ~gossip_status #1186~
- [ ] ~Async payments #1149~
- [ ] ~Peer storage backup #881 or #1110~
- [ ] ~Bolt 12 contacts / mutual message auth: https://delvingbitcoin.org/t/bolt-12-trusted-contacts/1046~
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [x] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Simplified mutual close #1096~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Attributable errors #1044~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [x] Simplified commitment #867
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Roasbeef** [comment]
liquidity ads:
  * recent change, was no splicing when it was originally created
  * cost of adding liquidity to existing channel isn't the same as creating a new channel
     * making a new channel has more cost than adding liquidity 
     * specific fee for new channel creation
        * goal to account for closing it in the future
        * when they add more liquidity don't want to make them pay again
        * effectively creates a discount when adding liquidity via a splice
     * 3 fields now:
        * base fee
        * proportional
        * channel creation fee
   * eclair testing internally w/ this and the other adds on
      * encountered the fee creation requirement above during testing

splicing:
  * channel reserve doesn't really exist in dual funding
  * people either setting 0 or 1%
  * splicing implications:
     * when you splice more funds in 
     * if you fix the %, then the reserve needs to go up as well 
     * introduces some edge cases w.r.t reserve of different splicing versions
  * t-bast idea:
    * you splice, and one side gets below the reserve
    * you allow forwards to increase their balance to get above the reserve
       * also allows them to dig below the reserve amount
       * so accept payments going to you, but reject outgoing 
   * channel_id in dual funding is diff
     * but when you splice, you keep the same channel ID

bolt 12 + offers:
  * rusty to rebase 
  * ready for merge in japan, tokyo celebration
  * few small comments on the PR:

taproot:
  * lnd fixed edge case w.r.t retransmission
  * roasbeef to work on making that clear in the spec 

taproot gossip:
   * bridge to turn v1 into v2
   * potentially test what a v2 node would look like if it was pure v2
