### ISSUE TITLE
Lightning Specification Meeting 2024/12/02

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#1210]
The meeting will take place on Monday 2024/12/02 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Simplified mutual close #1205
- [x] Liquidity ads #1153
- [x] Peer storage backup #881
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] BIP 353 in `invoice_request` #1180
- [x] Bolt 12 contacts: https://github.com/lightning/blips/pull/42
- [x] Splicing #1160
- [x] Dynamic Commitments #1117
- [x] Channel jamming #1071
- [x] Async payments #1149
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [x] Trampoline routing #829 and #836
- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Attributable errors #1044~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by vincenzopalazzo** [comment]
>I'm back in a timezone that is more friendly to the spec meeting ;)

Welcome back :)

**Comment by vincenzopalazzo** [comment]
Probably before the end of the meeting next week, we can discuss the following PRs

- https://github.com/lightning/bolts/pull/1200
- https://github.com/lightning/bolts/pull/1170 

I feel that these just need a decision to close or merge them, in this way, we have less PRs stuck in the queue

**Comment by Roasbeef** [comment]
rbf close:
  * t-bast and roasbeef to do final interop this week 
  * fabrice has updated with the taproot branch, and works w/ the extra nonces 
  * main change:
      * when you resend a shutdown, other party should also send a response 
      * makes the taproot add on easier, can just add the nonces along 
     

liquidity ads:
  * updated the TLV values to not conflict with the older version of liquidity ads 
    * lets you run the new and the old versions concurrently, now has distinct TLV types
  * ready for impl and review 

peer storage back ups: 
  * eclair has a version for cross compat
  * do the others have a fully updated version? 
    * lnd PR: https://github.com/lightningnetwork/lnd/pull/8490
    * CLN has a version in master w/ an experimental tag
  * (CLN <-> eclair) to do interop testing
  * bluematt has some outstanding comments, adi to respond+update PR 

 taproot gossip:
  * post tokyo elle outlined a spec+impl road map: https://delvingbitcoin.org/t/updates-to-the-gossip-1-75-proposal-post-ln-summit-meeting/1202?u=roasbeef
     * 3 stages:
        1. You can validate the new stuff. 
        2. You can announce old channels with the new stuff. 
        3. You can announce new (taproot) channels with the new stuff. 


bip 353 invoice request:
  * good to land after @rustyrussell's final changes

splicing: 
  * interop zone w/ eclair <-> CLN 
  * eclair before only had support for unannounced channels 
  * dusty was able to test w/ un announced channels, everything worked fine -- need to test the gossip part
     * super close, just have one core change in CLN 
     * related to rotating pubkeys, more depth than at the surface 

dyn commits:
  * lnd working on impl still

channel jamming:
  * carla catching up w/ post tokyo revisions 
  * lnd PR to start to set endorsements 

async payments:
  * trampoline routing w/ blinded payments ready to go
