### ISSUE TITLE
Lightning Specification Meeting 2024/12/16

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#1213]
The meeting will take place on Monday 2024/12/16 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Simplified mutual close #1205
- [x] Peer storage backup #1110
- [x] Dual funding reconnect `commit_sig` retransmission #1214
- [ ] ~Taproot #995~
- [ ] ~Taproot gossip #1059~
- [x] Trampoline routing #829 and #836
- [ ] ~Bolt 12 contacts: https://github.com/lightning/blips/pull/42~
- [ ] ~Splicing #1160~
- [ ] ~Dynamic Commitments #1117~
- [ ] ~Liquidity ads #1153~
- [ ] ~Channel jamming #1071~
- [x] Async payments #1149
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Attributable errors #1044~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~
