### ISSUE TITLE
Lightning Specification Meeting 2020/02/03

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#731]
The meeting will take place on Monday 2020/02/03 on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review
- [x] Single-option large channel proposal #596
- [x] BOLT 7: be more aggressive about sending our own gossip. #684
- [x] Bolt 1: Specify that extensions to existing messages must use TLV #714 (@t-bast)
 - Gossip channel queries
   - [x] BOLT7: reply_channel_range parameter #560
   - [x] ~BOLT 7: clarify how to decode empty arrays #729~: this has been discussed on the PR and, given that empty byte arrays are not a valid zip-encoded payload despite specifying a zip-encoded payload, the PR has been withdrawn.
   - [x] BOLT 7: clarify how to encode multiple `reply_channel_range` messages #730

## Long Term Updates
- [ ] ~Current status of the trampoline routing proposal (@t-bast)~
- [x] Current state of the anchor output proposal (@joostjager )

## Research
- [ ] ~How can we improve the gossip (`gossip_queries_ex`)? (@t-bast)~

@niftynei has split out the collaborative construction of transactions from her dual-funding proposal as an intermediate step. I'd like to encourage everyone to participate in the discussions on the mailing list, and we will likely revisit that proposal during the 2020/02/17 meeting.

----
# Post-Meeting notes:
## Action items
 - [x] t-bast: implement proposed mitigation for #728 and document that
 - [x] cdecker to change the featurebits to 18/19 and merge #596
 - [x] t-bast and araspitzu to brainstorm an advisory section in a new PR explaining how confirmations should scale with the funding amount
 - [x] cdecker to rebase and merge #684
 - [ ] everyone to continue the discussion of #714 on GH
 - [ ] everyone to discuss the minutiae of #560 and #730 on GH
 - [ ] rusty to rework 560 and 730 to assume ascending order.
 - [ ] everyone to keep an eye on the anchor outputs proposal and help wherever possible :-)

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-02-03-19.06.log.html)

**Comment by t-bast** [comment]
A suggestion of long-standing PRs that we could look at:

- Wumbo: https://github.com/lightningnetwork/lightning-rfc/pull/596
- Channel queries clarifications:
  - https://github.com/lightningnetwork/lightning-rfc/pull/560
  - https://github.com/lightningnetwork/lightning-rfc/pull/729
  - https://github.com/lightningnetwork/lightning-rfc/pull/730
- A gossip fix CL, Eclair and LL all implemented but should be clarified at the spec level: https://github.com/lightningnetwork/lightning-rfc/pull/684

**Comment by t-bast** [comment]
And thanks again, I really think preparing an agenda before-hand help make progress during the meeting.

**Comment by cdecker** [comment]
Added #596 and #684 :+1: I'll skim the others before committing to having them on the agenda :-)

**Comment by cdecker** [comment]
@Roasbeef I think you guys were working on anchor outputs, do you have anyone in mind that could give a brief summary of were we stand, what the open questions are, and how we can proceed/help with the proposal?

**Comment by andrerfneves** [comment]
@cdecker do meetings happen on the #lightning-dev IRC channel? - (aka, would love to sit idly and read/watch the conversation and discussion)

**Comment by joachimneu** [comment]
Also, at what time will this meeting take place?

**Comment by t-bast** [comment]
This is detailed here: https://github.com/lightningnetwork/lightning-rfc/blob/master/CONTRIBUTING.md#Specification-Modification-Process

Spec meetings are bi-weekly on the #lighting-dev IRC channel. Everyone is welcome to join!

**Comment by t-bast** [comment]
Tonight the meeting is at 7pm UTC time.

**Comment by andrerfneves** [comment]
Thanks @t-bast!
