### ISSUE TITLE
Lightning Specification Meeting 2020/02/17

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#735]
The meeting will take place on Monday 2020/02/17 on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review
- [x] Bolt 1: Specify that extensions to existing messages must use TLV #714
   - Shall we make TLV the only extension mechanism, and how do we work around non-mandatory fields that are not TLV fields (e.g., `option_upfront_shutdown_script`)
- [x] BOLT 1: add networks to init message. #682
  - Interop testing done
  - c-lightning: https://github.com/ElementsProject/lightning/pull/3300 and https://github.com/ElementsProject/lightning/pull/3371
   - Eclair: https://github.com/ACINQ/eclair/pull/1254)
- [x] A home for BOLT #738
   - @URoZYMP43wPs proposes publishing the spec as a gitbook on ln.dev (preview [here](https://preview.ln.dev/))
- ~[ ] Reply channel range simplification #737~
   - ~Adds details to the spec which were interpreted differently by the implementations.~
- ~[ ] BOLT11 additional and negative tests #736~
- [x] Avoid stuck channels after fee increase #740
  - Add some additional constraints to the fee-paying party to guarantee the ability to add an HTLC even in the presence of a 2x feerate spike.

## Long Term Updates
~- [ ] Protocol testing framework (@rustyrussell). See the `tools/` and `tests/events` directories in [lightning-rfc-protocol-test](https://github.com/ElementsProject/lightning-rfc-protocol-test) for details.~
- [x] Poor man's rendez-vous routing (@t-bast). See [mail by t-bast](https://lists.linuxfoundation.org/pipermail/lightning-dev/2020-February/002519.html) and [gist](https://gist.github.com/t-bast/9972bfe9523bb18395bdedb8dc691faf) for details. (Since this is a fresh proposal still in everybody's mind this moved up the list to minimize loss of context).

## Backlog
The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

~- [ ] Current status of the trampoline routing proposal (@t-bast)~
~- [ ] How can we improve the gossip (gossip_queries_ex)? (@sstone )~

----
# Post-Meeting notes:
## Action items
- [x] t-bast: give reviewers a few more days and then merge #714
- [x] rusty: get in touch with URoZYMP43wPs about the ln.dev hostname
- [x] everyone: keep exploring solutions to #740 
- [x] everyone: review https://github.com/lightningnetwork/lightning-rfc/pull/688#issuecomment-584302128 (anchor outputs)
- [x] cdecker: explore full sphinx rendezvous solutions
- [x] t-bast: iterate on decoys and ~poor-man's rendezvous~ route-blinding
- [ ] everyone: review https://gist.github.com/t-bast/9972bfe9523bb18395bdedb8dc691faf

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-02-17-19.06.log.html)

**Comment by t-bast** [comment]
Could we also look at https://github.com/lightningnetwork/lightning-rfc/pull/714 which is carrying over from next time? I updated the PR but didn't get reviews yet. I'm hoping that the first three reviews (#738, #737 and #736 could be done fairly quickly, but maybe I'm overly optimistic).

**Comment by darosior** [comment]
Maybe https://github.com/lightningnetwork/lightning-rfc/pull/682 too ?.. Since interop testing has already been done it shouldn't be long

**Comment by cdecker** [comment]
Ok, added both to the agenda, and I also added a brief summary of where we are with the various things.

**Comment by joostjager** [comment]
Short update on anchor format now that we've decided to not to symmetric csv (yet): https://github.com/lightningnetwork/lightning-rfc/pull/688#issuecomment-584302128
