### ISSUE TITLE
Lightning Specification Meeting 2020/03/02

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#744]
The meeting will take place on Monday 2020/03/02 on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review
- [x] Reply channel range simplification #737
   - Adds details to the spec which were interpreted differently by the implementations.
- [x] BOLT11 additional and negative tests #736
- [ ] ~TLV message extensions #754~
- [x] Stuck channels: #740 and #750
- [ ] ~Wumbo advisory for scaling confirmations: #746~
- [ ] ~Quick follow-up on Gitbook #738~

## Long Term Updates
- [ ] ~Current status of the trampoline routing proposal (@t-bast)~
- [ ] ~Protocol testing framework (@rustyrussell). See the `tools/` and `tests/events` directories in [lightning-rfc-protocol-test](https://github.com/ElementsProject/lightning-rfc-protocol-test) for details.~
- [x] Rendez-vous (@cdecker and @t-bast)
- [ ] ~How can we improve the gossip (`gossip_queries_ex`)? (@sstone )~

## Backlog
The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ]

----
# Post-Meeting notes:

## Action items

- [ ] Merge #699 and #736 once ack-ed on Github
- [ ] All implementations to check that their current behavior would be ok with merging #737 and report on the PR
- [ ] Finalize work on #740 : investigate signalling and clarify PR (@t-bast)
- [ ] Study cdecker's [rendezvous proposal](https://github.com/lightningnetwork/lightning-rfc/tree/rendez-vous) before next meeting
- [ ] Summarize Hornet's goodies and how they related to recent feature discussion (@cfromknecht)

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-03-02-19.05.log.html)
