### ISSUE TITLE
Lightning Specification Meeting 2020/03/16

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#756]
The meeting will take place on Monday 2020/03/16 on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review
- [x] Reply channel range simplification #737
- [x] BOLT11 additional and negative tests #736
- [x] TLV message extensions #754
- [x] Stuck channels #740
- [x] Wumbo advisory for scaling confirmations #746

## Long Term Updates
- [x] Anchor outputs (@joostjager)
- [ ] ~Current status of the trampoline routing proposal (@t-bast)~
- [ ] ~Rendez-vous (@cdecker)~
- [ ] ~Blinded paths (@t-bast)~
- [ ] ~Hornet (@cfromknecht)~
- [ ] ~Protocol testing framework (@rustyrussell). See the `tools/` and `tests/events` directories in [lightning-rfc-protocol-test](https://github.com/ElementsProject/lightning-rfc-protocol-test) for details.~

## Backlog
The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Upfront payments / DoS protection~

----
# Post-Meeting notes:

## Action items

- [ ] Follow up on the edge case of a block filled with channel opens for #737 (@Roasbeef @wpaulino)
- [ ] Rebase and merge #736 (@rustyrussell) 
- [ ] Finalize work on #740 (@halseth @joostjager @t-bast)
- [ ] Last pass on #754 then merge (@Roasbeef @t-bast) 
- [ ] Make #746 more high-level; the mention of scaling based on cumulative block reward is already too opinionated (@araspitzu)
- [ ] ALL: coordinate and setup a video chat to resolve the one vs two anchors discussion on #688  

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-03-16-19.10.log.html)

**Comment by joostjager** [comment]
* Anchor commitment format: one vs two anchors
* Channel jamming: is it a priority?

**Comment by t-bast** [comment]
Added anchor outputs. What's channel jamming?

**Comment by joostjager** [comment]
https://lists.linuxfoundation.org/pipermail/lightning-dev/2020-February/002547.html

**Comment by t-bast** [comment]
Gotcha, upfront payments/spam (why yet another name?). I'll add to the backlog.

**Comment by joostjager** [comment]
If think spam downplays the vulnerability. It sounds more like nuisance, not like taking a channel out of service for two weeks within a few minutes.

**Comment by t-bast** [comment]
True, this is really a potential denial-of-service

**Comment by joostjager** [comment]
Even denial-of-service suggests (to me at least) that it requires ongoing effort from the attacker. I think it is important to make a distinction between both classes of denial-of-service. With channel jamming the cost to the attacker is totally negligible compared to the damage done.
