### ISSUE TITLE
Lightning Specification Meeting 2020/03/30

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#757]
The meeting will take place on Monday 2020/03/30 on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review
- [x] Reply channel range simplification #737
- [x] Stuck channels #740
- [x] TLV message extensions #754
- [x] Wumbo advisory for scaling confirmations #746

## Issues

- [ ] ~Update fee concurrency https://github.com/lightningnetwork/lightning-rfc/issues/761~

## Long Term Updates
- [x] Anchor outputs (@joostjager)
- [x] Rendez-vous (@cdecker)
- [ ] ~Blinded paths (@t-bast)~
- [ ] ~Current status of the trampoline routing proposal (@t-bast)~
- [ ] ~Hornet (@cfromknecht)~
- [ ] ~Protocol testing framework (@rustyrussell). See the `tools/` and `tests/events` directories in [lightning-rfc-protocol-test](https://github.com/ElementsProject/lightning-rfc-protocol-test) for details.~

## Backlog
The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Upfront payments / DoS protection~

----
# Post-Meeting notes:

## Action items

- [x] Merge #737 and #754
- [ ] Finalize #740
- [ ] Finalize #746
- [ ] Anchor outputs: continue discussion on mailing list and PR
- [x] Trampoline and rendezvous: provide write-up in "proposals" format
- [ ] Summarize Hornet's goodies and how they related to recent feature discussion (@cfromknecht)

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-03-30-19.06.log.html)

**Comment by joostjager** [comment]
Should probably select one or two long term updates. Looking back at previous meetings, we didn't have time to cover much of those. Or at least arrange them in the priority order.

**Comment by t-bast** [comment]
That's true, I put everything that's been pending since previous meetings but it's likely we'll only do anchor + rendezvous/blinded, I'll re-arrange the order
