### ISSUE TITLE
Lightning Specification Meeting 2020/05/11

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#774]
The meeting will take place on Monday 2020/05/11 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Security.md #772
- [x] Channel announcement features (#769, #770, #773)
- [x] Clarify Bolt 7 intro #760
- [x] Bolt 11 test cases #736 
- [x] Network pruning #767 

## Long Term Updates

- [ ] ~Mempool tx pinning attack (@ariard @TheBlueMatt)~
- [x] Anchor outputs #688 (@joostjager)
- [ ] ~Trampoline routing #654 (@t-bast)~
- [ ] ~Blinded paths #765 (@t-bast)~
- [x] Protocol testing framework (@rustyrussell). See the `tools/` and `tests/events` directories in [lightning-rfc-protocol-test](https://github.com/ElementsProject/lightning-rfc-protocol-test) for details.

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Upfront payments / DoS protection~
- [ ] ~Hornet (@cfromknecht)~

----
# Post-Meeting notes:

## Action items

- [ ] Finalize #767 (@cfromknecht)
- [ ] Validate test vectors from #758 
- [ ] Finalize #772 (all implementations to add pointers to their own security policy)
- [ ] Trampoline: get the discussion going on the PR
- [ ] Summarize Hornet's goodies and how they related to recent feature discussion (@cfromknecht)

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-05-11-20.08.log.html)
