### ISSUE TITLE
Lightning Specification Meeting 2020/05/25

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#775]
The meeting will take place on Monday 2020/05/25 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Update BOLT 3 transaction test vectors to use static_remotekey #758
- [x] Clarification on the occurences of TLV records with the same type #777 
- [x] Complete the Fundamental Types #778 
- [x] BOLT 3: fix definition of flip(B) in P #779 

## Long Term Updates

- [ ] ~Trampoline routing #654 (@t-bast)~
- [x] Mempool tx pinning attack (@ariard @TheBlueMatt)
- [x] Anchor outputs #688 (@joostjager)
- [ ] ~Blinded paths #765 (@t-bast)~
- [ ] ~FoaF and rebalancing #780 (@renepickhardt)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Upfront payments / DoS protection~
- [ ] ~Hornet (@cfromknecht)~

----
# Post-Meeting notes:

## Action items

- [ ] Validate test vectors from #758 
- [ ] Simplify rationale paragraph on #777 then apply
- [ ] Fix spellchecker on #779 then apply
- [x] Draft preimage-watching and htlc lockdown proposals (@ariard)
- [ ] Design hazmat meatspace meeting suites for LN gathering and shared rally sign (@Roasbeef) 

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-05-25-20.09.log.html)

**Comment by renepickhardt** [comment]
Maybe it is too short on notice as I have just opened the PR but we could also have a preliminary review PR #780 for a new BOLT 14: Friend of a friend Balance sharing
