### ISSUE TITLE
Lightning Specification Meeting 2020/06/22

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#786]
The meeting will take place on Monday 2020/06/22 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Update BOLT 3 transaction test vectors to use static_remotekey #758
- [x] CLTV expiry delta recommendations #785
- [ ] ~Clarification on the occurences of TLV records with the same type #777~
- [ ] ~BOLT 3: fix definition of flip(B) in P #779~

## Long Term Updates

- [x] Anchor outputs #688 (@joostjager)
- [x] Mempool tx pinning attack (@ariard @TheBlueMatt)
- ~[ ] Trampoline routing #654 (@t-bast)~
- ~[ ] Blinded paths #765 (@t-bast)~
- ~[ ] FoaF and rebalancing #780 (@renepickhardt)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Upfront payments / DoS protection~
- [ ] ~Hornet (@cfromknecht)~

----
# Post-Meeting notes:

## Action items

- [ ] summarize the security loss the two-anchors proposal creates @ariard 
- [ ] find voice/video meeting time to discuss anchors security @t-bast 
- [ ] verify static_remotekey test vectors #758 
- [x] address multiple feedback on #785 @t-bast 

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-06-22-20.08.log.html)

**Comment by ariard** [comment]
There is a long-term subject we should also track it's better support for enforcing standardness or normalizing feerates on Core-side. See https://github.com/bitcoin/bitcoin/pull/18797 or https://github.com/bitcoin/bitcoin/issues/13283

**Comment by t-bast** [comment]
In order to follow up on @ariard's security concern for the two-anchors proposal, are you available next tuesday (june 30) at 8:30pm UTC (early morning for rusty)?

We'd need some people from the following group (not necessarily everyone): @ariard @TheBlueMatt @Roasbeef @joostjager @rustyrussell @niftynei @cdecker.

This meeting will be open to anyone who wants to join and we'll provide a summary.
