### ISSUE TITLE
Lightning Specification Meeting 2020/07/06

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#789]
The meeting will take place on Monday 2020/07/06 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] CLTV expiry delta recommendations #785
- [x] Clarification on the occurences of TLV records with the same type #777
- [x] BOLT 3: fix definition of flip(B) in P #779
- [x] Update BOLT 3 transaction test vectors to use static_remotekey #758

## Long Term Updates

I suggest we do a voice meeting to discuss anchor outputs / pinning attacks, this should help make progress on the discussions.
I've tried to summarize the latest state of the discussions [here](https://github.com/t-bast/lightning-docs/blob/master/pinning-attacks.md): if interested parties can have a look at it before the meeting, I think it would be helpful.

We can use an open [jitsi room](https://meet.jit.si/) and summarize what's said on IRC.

- [x] Anchor outputs #688 (@joostjager)
- [x] Mempool tx pinning attack (@ariard @TheBlueMatt)
- [ ] ~Trampoline routing #654 (@t-bast)~
- [ ] ~Blinded paths #765 (@t-bast)~
- [ ] ~FoaF and rebalancing #780 (@renepickhardt)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Upfront payments / DoS protection~
- [ ] ~Hornet (@cfromknecht)~

----
# Post-Meeting notes:

## Action items

- [ ] find voice/video meeting time to discuss anchors security @t-bast 
- [ ] verify static_remotekey test vectors #758 
- [ ] continue anchor outputs implementation work, feedback on the PR

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-07-06-20.14.log.html)

**Comment by MrManPew** [comment]
Hi @t-bast I actually think you should write something about this: https://github.com/lightningnetwork/lightning-rfc/pull/785 on twitter (issue a statement :)) , its not like all node operators read the specs or the meeting logs. Thanks

**Comment by t-bast** [comment]
@MrManPew done: https://twitter.com/realtbast/status/1283298246983659520

My hope is that some node operators and people who write guides for node operators will pick this up and relay it.
Clearly we don't expect everyone to follow what happens on the spec, but it would be great if at least some of them loosely followed what gets merged and spread the word!
