### ISSUE TITLE
Lightning Specification Meeting 2020/07/20

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#790]
The meeting will take place on Monday 2020/07/06 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] CLTV expiry delta recommendations #785
- [x] Missing MAC check in Bolt 8 #787

## Long Term Updates

- [x] Anchor outputs #688 (@joostjager)
- [x] Protocol tests (@rustyrussell) 
- [ ] ~Trampoline routing #654 (@t-bast)~
- [ ] ~Blinded paths #765 (@t-bast)~
- [x] FoaF and rebalancing #780 (@renepickhardt)

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Upfront payments / DoS protection~
- [ ] ~Hornet (@cfromknecht)~

----
# Post-Meeting notes:

## Action items

- [x] add bolt 11 writer requirement #785 (@t-bast)
- [ ] @renepickhardt to consider feedback and update proposal #780 
- [ ] anchor outputs interop testing #688 
- [ ] start looking at lnprototest

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-07-20-20.11.log.html)
