### ISSUE TITLE
Lightning Specification Meeting 2020/08/03

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#792]
The meeting will take place on Monday 2020/08/03 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] CLTV expiry delta recommendations #785
- [x] RFC update for ChaCha20-Poly1305 #763
- [x] Bolt 11 uppercase #661 and #677

## Long Term Updates

- [x] Anchor outputs #688 (@joostjager)
- [ ] ~Protocol tests (@rustyrussell)~
- [ ] ~Trampoline routing #654 (@t-bast)~
- [ ] ~Blinded paths #765 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Upfront payments / DoS protection~
- [ ] ~Hornet (@cfromknecht)~

----
# Post-Meeting notes:

## Action items

- [ ] finalize #785 on github (@t-bast @cfromknecht)
- [x] anchor outputs interop testing #688 
- [ ] start looking at lnprototest

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-08-03-20.09.log.html)
