### ISSUE TITLE
Lightning Specification Meeting 2020/10/12

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#802]
The meeting will take place on Monday 2020/10/12 at 7pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Clarify bolt 4 #801
- [x] Anchor revoked to_local #803 

## Issues Review

- [x] Asynchronous HTLCs and `channel_reestablish` #794

## Long Term Updates

- [ ] ~Evaluate historical min_relay_fee to improve update_fee in anchors (@rustyrussell and @TheBlueMatt)~
- [ ] ~Blinded paths #765 (@t-bast)~
- [x] Upfront payments / DoS protection
- [ ] ~Offers #798~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)~
- [ ] ~Trampoline routing #654 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet (@cfromknecht)~

----
# Post-Meeting notes:

## Action items

- [ ] address PR comments on #801 @bitonic-cjp 
- [ ] address PR comments on #803 @ariard
- [ ] every implementation to check its behavior on the channel de-sync scenario described in #794 
- [x] summarize upfront payments proposals, known attacks/abuses, threat model @t-bast 
- [ ] share chaumian token proposal with ML @rustyrussell 

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-10-12-19.06.log.html)

**Comment by t-bast** [comment]
Sorry for missing yesterday's meeting! I think the having a tracking issue can be helpful to prepare beforehand (at least it's useful for me), don't hesitate to add other topics to the list.

**Comment by ariard** [comment]
See https://github.com/lightningnetwork/lightning-rfc/pull/803. Also might be a good time to talk about Upfront payment, at least more fine-grained channel policy management (cf. ml discussions)

**Comment by t-bast** [comment]
Added and promoted upfront payments out of the backlog

**Comment by cdecker** [comment]
Can we add https://github.com/lightningnetwork/lightning-rfc/pull/798 to the long-term updates? It has gotten a number of updates lately.

**Comment by t-bast** [comment]
> Can we add #798 to the long-term updates?

Of course, done (I think all admins have the right to edit the issue, don't hesitate to add things)

**Comment by cdecker** [comment]
I prefer to make these requests in public, even if I apply them myself (makes the tracking issues a bit more lively and eventually we will want to discuss priorities ahead of the meeting, e.g., moving things to Backlog if there's too much to reasonably discuss in the next meeting).

**Comment by cdecker** [comment]
I'd also be interested in discussing Lloyd Fournier's [recent mail] to the
lightning-dev mailing list about the safety of two-round MuSig. It seems to me
that a longer-term relationship between two peers with an initial setup phase,
solves many of the concerns that are present in ad-hoc sessions that MuSig-DN
is concerned with.

[recent mail]: https://lists.linuxfoundation.org/pipermail/lightning-dev/2020-October/002820.html

**Comment by t-bast** [comment]
Good idea, this is an interesting topic :+1:
