### ISSUE TITLE
Lightning Specification Meeting 2020/10/26

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#805]
The meeting will take place on Monday 2020/10/26 at 7pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Clarify bolt 4 #801
- [x] Anchor revoked to_local #803
- [x] Recent CVEs: #807 #808 #809 
- [x] Security advisory #772 

## Issues

- [ ] ~reply_channel_range is too strict #804~

## Long Term Updates

- [ ] ~Upfront payments / DoS protection~
- [ ] ~Offers #798~
- [ ] ~Evaluate historical min_relay_fee to improve update_fee in anchors (@rustyrussell and @TheBlueMatt)~
- [ ] ~Blinded paths #765 (@t-bast)~
- [ ] ~Trampoline routing #654 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet (@cfromknecht)~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)~

----
# Post-Meeting notes:

## Action items

- [x] #801 @rustyrussell to try out the change and report success/failure
- [x] #803 @ariard address nits
- [x] #807 merge the PR and defer grouping the prescriptions to a later point in time
- [x] #808 make the formulation a bit more explicit
- [ ] #772 add contact details (e-mail and gpg keys) for the implementations and add details about what _not_ to do (report CVEs via the Twitter tag #StealMyMoney)

The full logs can be found [here](http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-10-26-19.07.log.html)

**Comment by ariard** [comment]
May we add #807, #808 and #809 ?

Also can we get back #772 now context which leads to its opening is public ?

**Comment by t-bast** [comment]
Added to the PR review list

**Comment by t-bast** [comment]
I just added #804 to the list as well: it may be worth re-visiting the option of adding an explicit `complete` boolean field to channel range queries instead of implicitly figuring out that a sync is complete.

**Comment by cdecker** [comment]
Adding the recent discussion on a simplified HTLC negotiation to address nodes drifting out of sync, and more consistent state might be a good idea. We've had quite some discussions around this lately, and I'd love to hear what others think about it.

**Comment by cdecker** [comment]
> * [ ]  Recent CVEs: #807 #808 #809

Regarding the CVEs: would it make sense to include a writeup of these in this repo, and link them into the respective places as rationaly?

**Comment by t-bast** [comment]
It's an interesting proposal, you would add a "cve" folder and have a write-up about each CVE we've found? I think it's nice, it would be easy to find
