### ISSUE TITLE
Lightning Specification Meeting 2021/03/29

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#856]
The meeting will take place on Monday 2021/03/29 at 7pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Closing fee requirement #847 
- [x] Funding timeout recovery proposal #854 

## Long Term Updates

- [x] Dual funding #851
- [ ] ~Trampoline routing #829 and #836 (@t-bast)~
- [x] Offers #798 (@rustyrussell)
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Blinded paths #765 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet (@cfromknecht)~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)~

----
# Post-Meeting notes:

## Action items

- [ ] @cdecker to draft KEYOLO proposal for #854 
- [x] @t-bast to split closing behavior in #847

Meeting logs can be found [here](http://gnusha.org/lightning-dev/2021-03-29.log).

**Comment by t-bast** [comment]
As usual, please suggest other topics / reorder them as you think makes sense.
