### ISSUE TITLE
Lightning Specification Meeting 2021/04/12

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#860]
The meeting will take place on Monday 2021/04/12 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [ ] Clarify `per_commitment_secret` #859

## Issues

- [ ] Discuss lightning network architecture diagram (https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-April/002990.html)

## Long Term Updates

- [ ] Dual funding #851
- [ ] Trampoline routing #829 and #836 (@t-bast)
- [ ] Offers #798 (@rustyrussell)
- [ ] Upfront payments / DoS protection #843
- [ ] Blinded paths #765 (@t-bast)

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] Hornet (@cfromknecht)
- [ ] lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)

**Comment by niftynei** [comment]
This link doesn't seem to work, but posting it here anyways. https://lightningd.github.io/meetings/april_12th_lightning_dev_meeting/2021/april_12th_lightning_dev_meeting.2021-04-12-20.05.txt
