### ISSUE TITLE
Lightning Specification Meeting 2021/04/26

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#864]
The meeting will take place on Monday 2021/04/26 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Clarify Bolt 3 test vectors #852 
- [x] Funding timeout recovery #854 / #866
- [x] Deterministic points #862 
- [ ] ~Splicing #863~

## Issues

- [x] https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-April/003002.html

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Trampoline routing #829 and #836 (@t-bast)~
- [ ] ~Offers #798 (@rustyrussell)~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Blinded paths #765 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet (@cfromknecht)~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)~

**Comment by ariard** [comment]
See also : https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-April/003002.html

**Comment by cdecker** [comment]
Added the two competing proposals for funding recovery #854 and #866.

**Comment by t-bast** [comment]
Meeting logs: https://lightningd.github.io/meetings/ln_spec_meeting/2021/ln_spec_meeting.2021-04-26-20.17.log.html
