### ISSUE TITLE
Lightning Specification Meeting 2021/05/10

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#870]
The meeting will take place on Monday 2021/05/10 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] On-the-fly channel upgrade #869 #868
- [x] Splicing #863

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Trampoline routing #829 and #836 (@t-bast)~
- [ ] ~Offers #798 (@rustyrussell)~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Blinded paths #765 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet (@cfromknecht)~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)~
