### ISSUE TITLE
Lightning Specification Meeting 2021/05/24

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#874]
The meeting will take place on Monday 2021/05/24 at 8pm UTC on IRC [#lightning-dev](irc://chat.freenode.net/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Clarify HTLC amount ordering #872
- [x] Shutdown Anysegwit #672 
- [x] Exclude dust HTLCs from commitment limits #873

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Trampoline routing #829 and #836 (@t-bast)~
- [ ] ~Offers #798 (@rustyrussell)~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Blinded paths #765 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet (@cfromknecht)~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)~

**Comment by t-bast** [comment]
As usual, this is a rough draft, feel free to add topics of interest.

**Comment by t-bast** [comment]
Meeting logs: http://gnusha.org/lightning-dev/2021-05-24.log

**Comment by cdecker** [comment]
Meeting minutes: [here](https://lightningd.github.io/meetings/https___github_com_lightningnetwork_lightning_rfc_issues_874/2021/https___github_com_lightningnetwork_lightning_rfc_issues_874.2021-05-24-20.12.html)
