### ISSUE TITLE
Lightning Specification Meeting 2021/06/21

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#879]
The meeting will take place on Monday 2021/06/21 at 8pm UTC on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Replace BIP69 #876
- [x] Remove HTLC amount restriction #877
- [x] Explicit `channel_type` negotiation #880
- [ ] ~Clarify when max-accepted-htlcs applies #745~

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Splicing #863~
- [ ] ~Trampoline routing #829 and #836 (@t-bast)~
- [ ] ~Offers #798 (@rustyrussell)~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Blinded paths #765 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet (@cfromknecht)~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)~

**Comment by t-bast** [comment]
As usual, feel free to add topics, especially @rustyrussell if there's a topic you'd like to cover among quiescence, protocol upgrade, or the other PRs you started working on.

**Comment by Crypt-iQ** [comment]
Would like to add this topic https://github.com/lightningnetwork/lightning-rfc/issues/873 as well, I updated it with a comment to address IRC comments.  I'll be available during the spec meeting to talk about it also.

**Comment by t-bast** [comment]
We can definitely talk about it during the meeting if you think it's necessary.
IMHO we're at the point where someone needs to work on a spec PR and an implementation to make progress, unless there are specific questions that need to be answered?

**Comment by t-bast** [comment]
Meeting logs can be found here: https://lightningd.github.io/meetings/ln_spec_meeting/2021/ln_spec_meeting.2021-06-21-20.06.log.html
