### ISSUE TITLE
Lightning Specification Meeting 2021/07/05

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#882]
The meeting will take place on Monday 2021/07/05 at 8pm UTC on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Explicit `channel_type` negotiation #880
- [ ] ~Clarify when max-accepted-htlcs applies #745~
- [ ] ~Avoid counting dust htlcs in limits #873~

## Meta discussion

bLIPs / SPARKs / BIPs: https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-June/003086.html

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Splicing #863~
- [ ] ~Trampoline routing #829 and #836 (@t-bast)~
- [ ] ~Offers #798 (@rustyrussell)~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Blinded paths #765 (@t-bast)~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet (@cfromknecht)~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)~

**Comment by ysangkok** [comment]
Meeting minutes: [full log](https://lightningd.github.io/meetings/ln_spec_meeting/2021/ln_spec_meeting.2021-07-05-20.06.log.html), [summarized](https://lightningd.github.io/meetings/ln_spec_meeting/2021/ln_spec_meeting.2021-07-05-20.06.html)
