### ISSUE TITLE
Lightning Specification Meeting 2021/07/19

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#888]
The meeting will take place on Monday 2021/07/19 at 8pm UTC on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

## Pull Request Review

- [ ] Updated `closing_signed` fee requirements #847
- [ ] Explicit `channel_type` negotiation #880
- [ ] Warning messages #834
- [ ] Clarify when max-accepted-htlcs applies #745
- [ ] Avoid counting dust htlcs in limits #873

## Meta discussion

bLIPs / SPARKs / BIPs: https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-June/003086.html

## Long Term Updates

- [ ] Dual funding #851
- [ ] Splicing #863
- [ ] Trampoline routing #829 and #836
- [ ] Offers #798 (@rustyrussell)
- [ ] Onion messages #759
- [ ] Upfront payments / DoS protection #843
- [ ] Blinded paths #765
- [ ] Peer storage backup #881

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] Hornet (@cfromknecht)
- [ ] lnprototest https://github.com/rustyrussell/lnprototest (@rustyrussell)

**Comment by ysangkok** [comment]
Meeting minutes: [summarized](https://lightningd.github.io/meetings/lightning_meeting_name/2021/lightning_meeting_name.2021-07-19-20.02.html) (contains link to full log)
