### ISSUE TITLE
Lightning Specification Meeting 2021/08/16

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#893]
The meeting will take place on Monday 2021/08/16 at 8pm UTC on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Warning messages #834
- [x] Explicit `channel_type` negotiation #880 
- [x] Updated `closing_signed` fee requirements #847
- [x] BLIPS #884
- [x] Update invoice test vectors with payment secret #887
- [ ] ~Check each other's dust limits #894~
- [ ] ~Advertize compression algorithms in `init` #825~
- [ ] ~Simple turbo channels enablement #895~

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Splicing #863~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Onion messages #759~
- [ ] ~Blinded paths #765~
- [ ] ~Offers #798~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest~

**Comment by t-bast** [comment]
As usual, feel free to add topics / PRs / issues you'd like to discuss during the meeting (ideally a few days before so that everyone can have a first look before the meeting).

**Comment by TheBlueMatt** [comment]
Can we also hit #825?

**Comment by t-bast** [comment]
Sure, I just added it to the list, I had missed your last comment there.

**Comment by t-bast** [comment]
Meeting logs can be found here: https://lightningd.github.io/meetings/meeting_name/2021/meeting_name.2021-08-16-20.04.log.html
