### ISSUE TITLE
Lightning Specification Meeting 2021/09/13

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#909]
The meeting will take place on Monday 2021/09/13 at 8pm UTC on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

## Pull Request Review

- [x] Warning messages #834
- [x] Feature bit for channel type #906
- [x] Check each other's dust limits #894 and #905
- [x] Simple turbo channels enablement #895
- [x] Add payment secret feature to Bolt 11 test vectors #898 
- [ ] ~Advertize compression algorithms in `init` #825~
- [ ] ~BLIPs #884~
- [ ] ~Restrict bitcoin amounts #908~
- [ ] ~Dynamic DNS support in gossip messages #911~

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Splicing #863~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Onion messages #759~
- [ ] ~Blinded paths #765~
- [ ] ~Offers #798~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet~
- [ ] ~lnprototest https://github.com/rustyrussell/lnprototest~

**Comment by t-bast** [comment]
As usual, don't hesitate to add/remove/reorder topics.

**Comment by cdecker** [comment]
https://github.com/lightningnetwork/lightning-rfc/pull/911 looks like a simple one to discuss (not implemented and thus not mergeable yes, but a good idea imho)

**Comment by t-bast** [comment]
Added to the PR list. I think it will probably slip to the next meeting though, since the PR was just submitted and I don't expect many people to have looked at it before the meeting?

**Comment by ryanthegentry** [comment]
I think #884 just needs a final ACK before merging? Does it need to be on the agenda or can the ACK happen async?

**Comment by t-bast** [comment]
> I think #884 just needs a final ACK before merging?

Not yet, at least on my part it's not an ACK yet.

I think [this comment](https://github.com/lightningnetwork/lightning-rfc/pull/884#pullrequestreview-742015640) indicates that we're still not sure whether this should be in the spec repo or a separate one. We should probably have some kind of vote to settle it (which means we need enough participants to have a meaningful vote).

And IMHO, we cannot merge this without including the "companion blip" that structures how to reserve scarce identifiers. This is only mentioned in blip-0001, but I think it's insufficient, we really need that *before* we can proceed.

I'm adding this to the agenda.

**Comment by ryanthegentry** [comment]
Yes I think there are differences of opinion on the "companion blip" - should there be a single central blip doc that replaces #605 and #716 and is referred to in the respective BOLTs? Or should the assignments be made into the BOLTs themselves (which is how I currently have it)? Looking forward to discussing in an hour!

**Comment by t-bast** [comment]
Meeting minutes: https://lightningd.github.io/meetings/not_the_marketing_committee/2021/not_the_marketing_committee.2021-09-13-20.06.html

Log: https://lightningd.github.io/meetings/not_the_marketing_committee/2021/not_the_marketing_committee.2021-09-13-20.06.log.html
