### ISSUE TITLE
 Lightning Specification Meeting 2021/09/27

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#916]
The meeting will take place on Monday 2021/09/27 at 8pm UTC on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

## Pull Request Review

- [ ] Restrict bitcoin amounts #908
- [ ] Feature bit for channel type #906
- [ ] Check each other's dust limits #894
- [ ] Advertize compression algorithms in `init` #825
- [ ] Dynamic DNS support in gossip messages #911
- [ ] Add payment metadata to payment request #912
- [ ] BLIPs #884
- [ ] Simple turbo channels enablement #910
- [ ] Warning messages #834

## Long Term Updates

- [ ] Dual funding #851
- [ ] Splicing #863
- [ ] Blinded paths #765
- [ ] Onion messages #759
- [ ] Offers #798
- [ ] Trampoline routing #829 and #836
- [ ] Upfront payments / DoS protection #843
- [ ] Peer storage backup #881

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] Hornet
- [ ] lnprototest https://github.com/rustyrussell/lnprototest

**Comment by t-bast** [comment]
As usual, don't hesitate to submit topics, or ask to reorder - we have many pending PRs and it's hard to judge which ones folks find more interesting.

**Comment by joostjager** [comment]
For the topics for which there is no preference, maybe it works to apply some kind of deterministic scheduling. For example "shortest diff first" or "longest time since last discussed first". 

To increase the chances of getting things done without adding any personal preference.

**Comment by t-bast** [comment]
I'm not sure any kind of deterministic scheduling makes sense, in my opinion we should only discuss what most people are interested in (otherwise most people will just stay silent during the meeting). I'd like to see people push for the topics they're interested in, and that should give enough data to decide what topics should be prioritized.

Ideally that means many people should vote for what topics they're interested in before the meeting, and then we'd sort them by interest. Unfortunately people tend to have too many things on their plate and not enough time to prepare before the meeting. Or maybe we're just not using the right tools, and if we had a very simple way of voting for topics people would do it beforehand? If people want to chime in on that, I'd like to have some feedback.

**Comment by t-bast** [comment]
Actually thinking about this more, we don't need to add new processes to get this end result.
We can get satisfying results if:

- the meeting chair changes often enough to reflect every team regularly
- the meeting chair takes meeting items in the order that she's interested in (instead of the order listed in this issue)

I think we're mostly good on the first point, but no-one does the second one yet.

To all future meeting chairs: don't hesitate to do it! If you're chair, you get to chose what we discuss! That's an effective way to ensure we cover varying topics.

**Comment by t-bast** [comment]
Here are the meeting logs:

- Minutes: https://lightningd.github.io/meetings/ln_marketing_committee/2021/ln_marketing_committee.2021-09-27-20.07.html
- Minutes (text): https://lightningd.github.io/meetings/ln_marketing_committee/2021/ln_marketing_committee.2021-09-27-20.07.txt
- Log: https://lightningd.github.io/meetings/ln_marketing_committee/2021/ln_marketing_committee.2021-09-27-20.07.log.html
