### ISSUE TITLE
Lightning Specification Meeting 2021/10/11

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#920]
The meeting will take place on Monday 2021/10/11 at 8pm UTC on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

## Pull Request Review

- [ ] Add dust exposure threshold #919
- [ ] Drop ping sending limitation #918
- [ ] Feature bit for channel type #906
- [ ] Simple turbo channels enablement #910
- [ ] Warning messages #834
- [ ] BLIPs #884
- [ ] Advertize compression algorithms in `init` #825
- [ ] Add payment metadata to payment request #912
- [ ] Dynamic DNS support in gossip messages #911 or #917

## Long Term Updates

- [ ] Dual funding #851
- [ ] Splicing #863
- [ ] Blinded paths #765
- [ ] Onion messages #759
- [ ] Offers #798
- [ ] Trampoline routing #829 and #836
- [ ] Upfront payments / DoS protection #843
- [ ] Peer storage backup #881

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] Hornet
- [ ] lnprototest https://github.com/rustyrussell/lnprototest

**Comment by TheBlueMatt** [comment]
It seems everyone has come around to @t-bast's meeting time change, I'm gonna go get lunch, be back in an hour.

**Comment by LightningHelper** [comment]
logs?
