### ISSUE TITLE
Lightning Specification Meeting 2022/03/28

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#971]
The meeting will take place on Monday 2022/03/28 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Pull Request Review

- [x] Remove legacy sphinx format #962
- [x] Clarify mutual close requirements #964
- [x] Port conventions for different networks #968
- [ ] ~Onion messages #759~
- [ ] ~Dual funding #851~
- [x] Route blinding #765
- [x] Blinded fees #967
- [ ] ~Offers #798~
- [ ] ~Add dust exposure threshold #919~

## Waiting for interop

- [ ] ~Websocket transport #891~
- [x] Simple turbo channels enablement #910
- [x] Don't force close until error is received after `channel_reestablish` #934
- [ ] ~Dynamic DNS support in gossip messages #911~

## Long Term Updates

- [ ] ~Liquidity ads #878~
- [ ] ~Splicing #863~
- [ ] ~Simplified commitment #867~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~
- [ ] ~Taproot updates~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
We're around the time of the year where some countries change time due to daylight savings, make sure to double-check the meeting time (and the next one as well).
